# Generated by Django 2.0.2 on 2019-02-18 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professor_id', models.IntegerField()),
                ('professor_name', models.CharField(max_length=20)),
                ('students', models.ManyToManyField(to='app1.Student')),
            ],
        ),
    ]
